name: Build and Deploy C++ Library for Raspberry Pi 5 (ARM64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-library-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cross-compiler and tools
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu make

      - name: Build static library for ARM64
        run: |
          make clean
          make lib CXX=aarch64-linux-gnu-g++ CXXFLAGS="-std=c++20 -Wall -Wextra -O2 -g"

      - name: Upload ARM64 library artifact
        uses: actions/upload-artifact@v4
        with:
          name: libgestures-arm64
          path: libgestures.a

  deploy-library-arm64:
    needs: build-library-arm64
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download ARM64 library artifact
        uses: actions/download-artifact@v4
        with:
          name: libgestures-arm64

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: libgestures.a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# This workflow cross-compiles the static library for ARM64 (Raspberry Pi 5) and uploads it as a release asset.
# The resulting libgestures.a can be downloaded and linked on a Raspberry Pi 5 running 64-bit Linux.
