name: Build and Deploy C++ Library for Raspberry Pi 5 (ARM64)
on:
  push:
    branches: [ main ]
    tags:        
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build-library-arm64:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build static library for ARM64
        run: |
          make clean
          HAILO_SDK_AVAILABLE=1 make lib

      - name: Upload ARM64 library artifact
        uses: actions/upload-artifact@v4
        with:
          name: libgestures-arm64
          path: libgestures.a

  deploy-library-arm64:
    needs: build-library-arm64
    runs-on: self-hosted
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download ARM64 library artifact
        uses: actions/download-artifact@v4
        with:
          name: libgestures-arm64

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: libgestures.a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create DEB package
        uses: damianh/deb-pkg@v1
        with:
          package: kibu-gestures
          version: ${{ github.ref_name }}
          maintainer: Your Name <your@email.com>
          arch: arm64
          description: "Hand gesture recognition C++ library"
          files: |
            libgestures.a:/usr/local/lib/libgestures.a
            Config.hpp:/usr/local/include/Config.hpp
            Base.hpp:/usr/local/include/Base.hpp
            Detector.hpp:/usr/local/include/Detector.hpp
            Landmark.hpp:/usr/local/include/Landmark.hpp
            Gesture.hpp:/usr/local/include/Gesture.hpp
            visualization.hpp:/usr/local/include/visualization.hpp
          dependencies: "libopencv-dev"

      - name: Upload DEB to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: kibu-gestures_${{ github.ref_name }}_arm64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
