name: Build and Deploy C++ Library for Raspberry Pi 5 (ARM64)
on:
  push:
    branches: [ main ]
    tags:        
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build-library-arm64:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build static library for ARM64
        run: |
          make clean
          make lib

      - name: Upload ARM64 library artifact
        uses: actions/upload-artifact@v4
        with:
          name: libgestures-arm64
          path: libgestures.a

  deploy-library-arm64:
    needs: build-library-arm64
    runs-on: self-hosted
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download ARM64 library artifact
        uses: actions/download-artifact@v4
        with:
          name: libgestures-arm64

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: libgestures.a
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
      - name: Create DEB package
        run: |
          set -e
          PKGNAME=kibu-gestures
          VERSION=${{ github.ref_name }}
          ARCH=arm64
          DEBROOT=debbuild/${PKGNAME}_${VERSION}
          mkdir -p $DEBROOT/usr/local/lib
          mkdir -p $DEBROOT/usr/local/include
          cp libgestures.a $DEBROOT/usr/local/lib/
          cp Config.hpp $DEBROOT/usr/local/include/
          cp Base.hpp $DEBROOT/usr/local/include/
          cp Detector.hpp $DEBROOT/usr/local/include/
          cp Landmark.hpp $DEBROOT/usr/local/include/
          cp Gesture.hpp $DEBROOT/usr/local/include/
          cp visualization.hpp $DEBROOT/usr/local/include/
          mkdir -p $DEBROOT/usr/local/lib/pkgconfig
          cat <<EOF > $DEBROOT/usr/local/lib/pkgconfig/gestures.pc
          prefix=/usr/local
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib
          includedir=${prefix}/include

          Name: gestures
          Description: Hand gesture recognition C++ library
          Version: $VERSION
          Libs: -L${libdir} -lgestures
          Cflags: -I${includedir}
          EOF
          mkdir -p $DEBROOT/DEBIAN
          cat <<EOF > $DEBROOT/DEBIAN/control
          Package: $PKGNAME
          Version: $VERSION
          Section: libs
          Priority: optional
          Architecture: $ARCH
          Maintainer: Your Name <your@email.com>
          Description: Hand gesture recognition C++ library
          Depends: libopencv-dev
          EOF
          dpkg-deb --build $DEBROOT
          mv debbuild/${PKGNAME}_${VERSION}.deb ${PKGNAME}_${VERSION}_${ARCH}.deb

      - name: Upload DEB to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: kibu-gestures_${{ github.ref_name }}_arm64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}